Feature/realtime review update
kyutech-programming-club/lt-manager pull request #44
Opened 2020-03-19 08:13 UTC by tanacchi

コメントをリアルタイムで更新できるようにした

2020-03-19 08:13 UTC, tanacchi commented
Ruby のバージョン変えたので注意

2020-03-19 08:15 UTC, tanacchi commented
コメントの順番を逆にしたので
新しいのが上に来るようになっています．

2020-03-25 06:11 UTC, syu-kwsk requested changes
update情報の追記をお願いいたします。

2020-03-25 06:21 UTC, syu-kwsk approved these changes

2020-03-25 06:24 UTC, merged